import fs from 'node:fs';
import { randomBytes } from 'node:crypto';
const adminPassword=randomBytes(24).toString('hex');
const testEnv={...process.env,ADMIN_EMAILS:'qa@example.test',ADMIN_PASSWORD:adminPassword,GOOGLE_SERVICE_ACCOUNT_JSON:'',GOOGLE_DRIVE_FOLDER_ID:''};
import { spawn } from 'node:child_process';
const { chromium } = await import(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES + '/playwright/index.mjs' : 'playwright');
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','-p','3100'],{stdio:'pipe',env:testEnv});
await new Promise((resolve,reject)=>{ const timeout=setTimeout(()=>{server.kill();reject(new Error('Server startup timed out'));},20000); const ready=data=>{console.log(data.toString());if(data.toString().includes('Ready')){clearTimeout(timeout);resolve();}}; server.stdout.on('data',ready);server.stderr.on('data',ready);server.on('error',reject);server.on('exit',code=>reject(new Error('Server exited '+code)));});
console.log('Launching browser');
try {

 const browser = await chromium.launch({headless:true, ...(process.env.PTRA_CHROMIUM_PATH ? {executablePath:process.env.PTRA_CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage']} : {})});
 console.log('Browser launched');
 const page = await browser.newPage({viewport:{width:1440,height:1050},deviceScaleFactor:1});
 const errors=[]; page.on('pageerror', e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:3100', {waitUntil:'networkidle'});
 await page.screenshot({path:'qa/home-desktop.png',fullPage:true});
 const assert=(v,m)=>{if(!v)throw new Error(m);};
 assert(await page.locator('h1').count()===1,'Single home h1');
 assert(await page.locator('#job-postings a[href="https://www.linkedin.com/posts/madanpadaki_hiring-alert-janai-engineering-interns-program-share-7508457194854506496-9G5k"]').count()===1,'LinkedIn opportunity renders without Drive configuration');
 await page.locator('#job-postings').screenshot({path:'qa/job-posting-desktop.png'});
 assert(await page.getByRole('heading',{name:'Advertise here.',exact:true}).count()===1,'Homepage advertising block');
 assert((await page.getByRole('link',{name:'Enquire about advertising'}).getAttribute('href')).startsWith('mailto:prakruthiptra@gmail.com?'),'Advertising enquiry uses email without Drive');
 await page.locator('.advertise-home').screenshot({path:'qa/advertise-home-desktop.png'});
 assert(await page.locator('a[href="/resources"]').count()>0,'Resources links');
 await page.goto('http://127.0.0.1:3100/blog');
 assert(await page.locator('.post-card').count()===15,'All fifteen articles present');
 await page.getByRole('searchbox').fill('water supply problem');
 assert(await page.locator('.post-card').count()===1,'Search filters articles');
 await page.getByRole('searchbox').fill('no-match-xyz');
 await page.getByRole('button',{name:'Clear filters'}).click();
 assert(await page.locator('.post-card').count()===15,'Reset restores articles');
 await page.getByRole('button',{name:'Voter information',exact:true}).click();
 assert(await page.locator('.post-card').count()===2,'Category filters articles');
 await page.screenshot({path:'qa/updates-desktop.png',fullPage:true});
 const slugs=fs.readdirSync('src/content/posts').filter(x=>x.endsWith('.md')).map(x=>x.slice(0,-3));
 for (const slug of slugs) {
  const response=await page.goto('http://127.0.0.1:3100/blog/'+slug);
  assert(response.status()===200,'Article '+slug);
  assert(await page.locator('.prose-content').innerText(),'Article content');
 }
 await page.goto('http://127.0.0.1:3100/jobs');
 assert(await page.locator('input[type=file]').count()===1,'Jobs attachment restored');
 assert(await page.getByRole('combobox').inputValue()==='Jobs / local work','Jobs default topic');
 await page.screenshot({path:'qa/jobs-desktop.png',fullPage:true});
 await page.getByRole('combobox').selectOption('Volunteer');
 assert(await page.locator('input[type=file]').count()===0,'Non-job topic hides attachment');
 await page.goto('http://127.0.0.1:3100/apply');
 await page.getByLabel('Full name').fill('QA Resident');
 await page.getByRole('combobox').selectOption('Volunteer');
 await page.getByRole('button',{name:'Send to the association'}).click();
 await page.locator('.submission-error').waitFor();
 assert((await page.locator('.submission-error').innerText()).includes('temporarily unavailable'),'Unconfigured storage fails clearly');
 await page.route('**/api/applications',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({ok:true,id:'qa-only'})}));
 await page.getByRole('button',{name:'Send to the association'}).click();
 await page.getByText('Message sent successfully. The Office Bearers have received it for review.').waitFor();
 await page.unroute('**/api/applications');
 await page.goto('http://127.0.0.1:3100/advertise');
 assert(await page.getByRole('heading',{name:'Township classifieds'}).count()===1,'Advertise restored');
 await page.goto('http://127.0.0.1:3100/admin');
 await page.screenshot({path:'qa/admin-desktop.png',fullPage:true});
 const unauth=await page.request.get('http://127.0.0.1:3100/api/admin/applications');
 assert(unauth.status()===401,'Admin API is protected');
 const rejected=await page.request.post('http://127.0.0.1:3100/api/admin/login',{data:{email:'qa@example.test',password:'invalid'}});
 assert(rejected.status()===401,'Invalid credentials rejected');
 const login=await page.request.post('http://127.0.0.1:3100/api/admin/login',{data:{email:'qa@example.test',password:adminPassword}});
 assert(login.status()===200,'Configured admin login');
 const cookie=login.headersArray().filter(h=>h.name.toLowerCase()==='set-cookie').map(h=>h.value.split(';')[0]).join('; ');
 const protectedData=await page.request.get('http://127.0.0.1:3100/api/admin/applications',{headers:{Cookie:cookie}});
 assert(protectedData.status()===200,'Signed session authorizes admin API');
 await page.request.post('http://127.0.0.1:3100/api/admin/logout');
 const missing=await page.goto('http://127.0.0.1:3100/blog/does-not-exist');
 assert(missing.status()===404,'Unknown article gives 404');
 await page.goto('http://127.0.0.1:3100/resources');
 assert(await page.locator('.helpline-card').count()===9,'Nine helplines');
 await page.getByRole('searchbox').fill('1916');
 assert(await page.locator('.helpline-card').count()===1,'Helpline number search');
 await page.getByRole('searchbox').fill('');
 await page.getByRole('button',{name:'Emergency',exact:true}).click();
 assert(await page.locator('.helpline-card').count()===3,'Emergency filter');
 await page.getByRole('button',{name:'All contacts',exact:true}).click();
 await page.screenshot({path:'qa/resources-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),'Mobile directory has no overflow');
 await page.goto('http://127.0.0.1:3100');
 assert(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),'Mobile home has no overflow');
 await page.getByRole('button',{name:'Menu'}).click();
 assert(await page.locator('#mobile-navigation').isVisible(),'Mobile menu opens');
 await page.keyboard.press('Escape');
 assert(!(await page.locator('#mobile-navigation').isVisible()),'Escape closes menu');
 await page.getByRole('button',{name:'Menu'}).click();
 await page.locator('#mobile-navigation').getByRole('link',{name:'Updates',exact:true}).click();
 await page.waitForURL('**/blog');
 assert(!(await page.locator('#mobile-navigation').isVisible()),'Navigation closes menu');
 assert(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),'Mobile blog has no overflow');
 await page.goto('http://127.0.0.1:3100');
 await page.screenshot({path:'qa/home-mobile.png',fullPage:true});
 await page.setViewportSize({width:320,height:700});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),'320px home has no overflow');
 for(const route of ['/jobs','/apply','/advertise','/admin']) {
  await page.goto('http://127.0.0.1:3100'+route);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),'320px layout '+route);
 }
 await page.goto('http://127.0.0.1:3100/resources');
 assert(await page.locator('a[href^="tel:"][target="_blank"]').count()===0,'Calls stay direct');
 assert(errors.length===0,'No browser errors: '+errors.join(';'));
 console.log('PASS: production routes, 15 articles, Jobs/Apply/Advertise/Admin, file visibility, mocked success UI, unconfigured submission, signed admin sessions, 9 helplines, resource search, emergency filter, search, category filter, reset, 404, mobile menu, Escape, navigation, 320px/390px overflow, no browser errors.');
 await browser.close();
} finally { server.kill(); }
